"""Constantes e esquemas de colunas do sistema."""

COLUNAS_VENDAS_OBRIGATORIAS = ["SKU", "VALOR_VENDA_BRUTO"]
COLUNAS_CUSTOS_OBRIGATORIAS = [
    "SKU",
    "PRECO_CUSTO",
    "TAXA_PLATAFORMA",
    "VALOR_FRETE",
    "CUSTO_EMBALAGEM",
]

COLUNAS_VENDAS_OPCIONAIS = ["URL_ANUNCIO", "QTD_VENDIDA"]
COLUNAS_CUSTOS_OPCIONAIS = ["URL_ANUNCIO", "ESTOQUE_ATUAL"]

COLUNAS_CUSTOS_NUMERICAS = [
    "PRECO_CUSTO",
    "TAXA_PLATAFORMA",
    "VALOR_FRETE",
    "CUSTO_EMBALAGEM",
]

COLUNAS_VENDAS_NUMERICAS = ["VALOR_VENDA_BRUTO"]

# Classificação de status (lucro líquido em R$)
LIMIAR_LUCRATIVO = 20.0
LIMIAR_POUCO_LUCRATIVO = 0.0

STATUS_LUCRATIVO = "Lucrativo"
STATUS_POUCO_LUCRATIVO = "Pouco Lucrativo"
STATUS_PREJUIZO = "Prejuizo"
STATUS_ERRO = "ERRO DE DADOS"

STATUS_CORES = {
    STATUS_LUCRATIVO: "#166534",
    STATUS_POUCO_LUCRATIVO: "#a16207",
    STATUS_PREJUIZO: "#b91c1c",
    STATUS_ERRO: "#6b7280",
}

STATUS_CORES_RGB = {
    STATUS_LUCRATIVO: (22, 101, 52),
    STATUS_POUCO_LUCRATIVO: (161, 98, 7),
    STATUS_PREJUIZO: (185, 28, 28),
    STATUS_ERRO: (128, 128, 128),
}

# Matriz de giro de estoque
GIRO_ALTO = 30  # unidades vendidas no período
GIRO_BAIXO = 5
